# python 3.11.8-slim-bullseye intes64
FROM python@sha256:a2d01031695ff170831430810ee30dd06d8413b08f72ad978b43fd10daa6b86e
LABEL maintainer="Alessio Vignoli" \
        name="alessiovignoli3/stimulus:latest" \
        description="Docker image containing python packages required for stimulus noise module"

# installing python needed packages
# TODO one can add the requirements.txt and install the packages from there
RUN pip install \
    ps==0.1.0